### ISSUE TITLE
How to show loader till items are loading for play

### ISSUE THREAD

**Issue by DiptiGupta** [Hagsten/Talkify#13]
In Angular 2, i am using talkify player for text to speech. I need to show loader on page until contents are ready for play. I  found a method i.e. onItemLoaded which fires just before loading of content.
But this method is not accessing correct value of component(angular 2)'s variable.

Please suggest some ways to achieve it.

**Comment by Hagsten** [comment]
Hi, I am not familiar with the workings of Angular 2, but you would subscribe to the onItemLoaded event of the player using

``
player.subscribeTo(
{
    onItemLoaded: function () { console.log('onItemLoaded'); }
});
``

Hope it helps :)

**Comment by DiptiGupta** [comment]
Hi Hagsten,

Thank you for your suggestion.

I am able to print or alert a hard coded string. But i want to access variable in onItemLoaded function which is defined outside.

I want to set true and false of variable so that loader can be visible till  loading of contents which will be played.

Can you please guide me to do this in javascript? 
 I will do the same in Angular.

**Comment by Hagsten** [comment]
Hi,

See this fiddle for an example of a loader: https://jsfiddle.net/t1fj6aao/1/.

This is using jQuery but is accessing variables defined outside. I am only familiar with Angular 1.x and there you need to apply the scope or pushing a new digest cycle to the stack by using the timeout service with 0 ms ($timeout(function () { }, 0);).

https://talkify.net is an Angular 1 app and we are using the $timeout function to force an update of the scope variables so that the view can re-render. We are also listening to the item.isLoading variable instead of the events. I can give you an example later when I got the time. But have a look at my example here and see if that helps you :)

Hope this helps :)
