### ISSUE TITLE
Talkify Playlist seems to not read one word lines

### ISSUE THREAD

**Issue by lyndachi** [Hagsten/Talkify#2]

**Comment by Hagsten** [comment]
Hi lyndachi!

Thanks for writing. Talkify has a requirement (hard coded), to limit number of "useless" lines. This requirement is that a "line" (or piece of text) needs to be 10 or more characters in length. This requirement is only enforced for elements that is not paragraphs and headings (p, h1-h6). This is due to the fact that divs are not semantical and we can therefore not "trust" the text content in those. It has proven to be a lot of unnecessary/unimportant text in divs, we have therefore built in this restriction.

You can however work around this by either use semantical elements such as a paragraph tag or tell Talkify that you really want to include a specific element by providing them yourself by invoking "withElements(element[])" on the playlist builder or by invoking "insert($element)" on the playlist instance.

I hope this helps you. :)

**Comment by lyndachi** [comment]
Thanks I'll try that!
