### ISSUE TITLE
Love your script... However, I want to make use of my own voices...

### ISSUE THREAD

**Issue by inglesuniversal** [Hagsten/Talkify#23]
Awesome script... I talked to you before congratulating you for this project... My request is very simple... How could I use this script under two different scenarios?

1.- Using my own voices (Amazon Polly)

2.- What if I want to make use of an audio file in mp3 ?

Thanks for your support.

**Comment by Hagsten** [comment]
Hi!

Thank you :). If you want to use your own voices you can always configure talkify (talkify-config.js) to go to your own web server where you stream your own audio from. You will then need to handle the backend by yourself. Another choice is to only provide your own route for the speech endpoint - you will need to change where talkify-player.js calls the Talkify backend for an audio stream.

If you also want speech marks (for text highlighting) you will need to handle that as well. I know that Amazon service provides speech marks, so you should be able to make it work. You will need to conform to the expected speech mark contract which is an array of a JSON object containing the character position and the current word:

`[{"Word":"Read","Position":100,"CharPosition":0},{"Word":"any","Position":325,"CharPosition":5}]`

You will also loose the ability to recognize language since it is too tied up with the speech generation. 

Regarding the mp3 file, do you want to have your own voice there too? If so, then you will need to implement that route in your own web server as well. If you are happy with our voices then a POST to https://talkify.net/api/speech/v1/download will trigger a download. We have some documentation regarding this @
https://manage.talkify.net/docs#api-reference-speech-download-as-file
