### ISSUE TITLE
ES voice is not being recognized as it plays.

### ISSUE THREAD

**Issue by inglesuniversal** [Hagsten/Talkify#8]
Hi I tried this sentence in SP...

Buenos días, me gusta mucho esta interfaz.

and Talkify does not reproduce its TTS

**Comment by Hagsten** [comment]
Hi.

Yes and no. That particular sentence will give you Spanish TTS if you play it using our demo at http://talkify.net/natural-sounding-voices-demo. However, since it is harder and harder to determine a language the smaller the input is, we have implemented a concept of a "reference language" which basically is the most common language on the current page. This language is selected for inputs that are below a certain threshold - which is 10 words. "Buenos días, me gusta mucho esta interfaz." is below that threshold since it only has 7 words. Sentences larger than 10 words are seen as long enough for good accuracy.

That is how it works now. But it is in our backlog to look over this feature again since it was built before we updated our language recognition software.

A workaround is to force the Spanish voice or to supply a larger text input. I promise i'll look into the threshold and see if we can lower it. 

I hope that clarifies the issue :).

**Comment by inglesuniversal** [comment]
hello, thanks so much for taking the time to answer my question... there are two voices that I used to get form sitepal.com and nuance.com (paulina and carlos) both in spanish... The one that your script plays as default has a heavy spanish (from spain) accent... Is it possible for you or for both of us to add additional voices without being so complicated... In our region since its Mexico, people enjoy to hear an accent they can relate to, but bottom line, your script has a lot of uses, in my case its main use is for education (english learning) and spanish voice assistant. I hope you can consider adding es-US or es-MX accents in the coming days.

**Comment by Hagsten** [comment]
I can probably add a Mexican accent (es-MX) using a voice called Hilda. I'll look into that!

**Comment by Hagsten** [comment]
@inglesuniversal  there is now a es-MX voice to choose from. The sample rate is only 8000 (compared to 16 000 for the es-ES voice). Closing issue.
